version: '3.2'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      ## the >- used below infers a value which is a string and properly
      ## ignore the multiple lines resulting in one long string:
      ## https://yaml.org/spec/1.2/spec.html
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka:19092,
        LISTENER_DOCKER_EXTERNAL://localhost:9092

      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19092,
        LISTENER_DOCKER_EXTERNAL://:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: >-
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO

    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka

  eureka:
    container_name: eureka
    build: ../eureka-server/
    ports:
      - "8761:8761"
    networks:
      - eureka

  zuul-proxy:
    container_name: zuul
    build: ../zuul-server/
    ports:
      - "8765:8765"
    depends_on:
      - eureka
    networks:
      - eureka

  psql-status-service:
    container_name: psql-status-service
    build: postgres/
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - status

  status-service:
    container_name: status-service
    build: ../status-service/
    networks:
      - status
      - kafka
      - eureka
    ports:
      - "8080:8080"
    depends_on:
      - psql-status-service
      - eureka
      - zuul-proxy



volumes:
  db-data:

networks:
  status:
  kafka:
  eureka:
