version: '2.4'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      ## the >- used below infers a value which is a string and properly
      ## ignore the multiple lines resulting in one long string:
      ## https://yaml.org/spec/1.2/spec.html
      KAFKA_ADVERTISED_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://kafka:19092,
        LISTENER_DOCKER_EXTERNAL://kafka:9092

      KAFKA_LISTENERS: >-
        LISTENER_DOCKER_INTERNAL://:19092,
        LISTENER_DOCKER_EXTERNAL://:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        LISTENER_DOCKER_INTERNAL:PLAINTEXT,
        LISTENER_DOCKER_EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: >-
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO

    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka

  eureka:
    container_name: eureka
    build: ../eureka-server/
    ports:
      - "8761:8761"
    networks:
      - eureka
      - kafka

  zuul-proxy:
    container_name: zuul
    build: ../zuul-server/
    ports:
      - "8765:8765"
    depends_on:
      - eureka
    networks:
      - eureka

  psql-status-service:
    container_name: psql-status-service
    build: postgres-status/
    volumes:
      - db-data-for-status:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - status

  status-service:
    container_name: status-service
    build: ../status-service/
    ports:
      - "8081:8080"
    depends_on:
      - psql-status-service
      - zuul-proxy
    networks:
      - status
      - kafka
      - eureka

  scan-service:
    container_name: scan-service
    build: ../scan-service/
    ports:
      - "8085:8080"
    depends_on:
      - zuul-proxy
    networks:
      - kafka
      - eureka

  screenshot-consumer:
    container_name: screenshot-consumer
    build: ../screenshot-consumer/
    ports:
      - "8083:8080"
    depends_on:
      - kafka
      - zuul-proxy
    networks:
      - kafka
      - eureka
      - screenshot

  image-service:
    container_name: image-service
    build: ../image-service/
    ports:
      - "8084:8080"
    depends_on:
      - kafka
      - zuul-proxy
      - psql-image-service
    networks:
      - kafka
      - eureka
      - image-service

  psql-image-service:
    container_name: psql-image-service
    build: postgres-image/
    volumes:
      - db-data-for-images:/var/lib/postgresql/data/
    ports:
      - "4040:5432"
    networks:
      - image-service

  chrome:
    container_name: chrome
    image: robcherry/docker-chromedriver:latest
    privileged: true
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
    ports:
      - "4444:4444"
    networks:
      - screenshot


volumes:
  db-data-for-status:
  db-data-for-images:

networks:
  status:
  kafka:
  eureka:
  image-service:
  screenshot:
